### ISSUE TITLE
How to use both nginx and xray server

### ISSUE THREAD

**Issue by uaudith** [chika0801/Xray-examples#13]
is it possible to have VLESS-XTLS-uTLS-REALITY and nginx together? If I am hosting a website in my VPS with Nginx.
Do you know how to configure them to co-exist, because both need to listen on port 443?

Can you also explain what is meant by steal_oneself and nginx_sni_shunting

Thank you

**Comment by chika0801** [comment]
> is it possible to have VLESS-XTLS-uTLS-REALITY and nginx together? If I am hosting a website in my VPS with Nginx.
Do you know how to configure them to co-exist, because both need to listen on port 443?

The solution I know of is to use nginx to listen on port 443 with the sni shunting provided by nginx. the nginx_sni_shunting config file does just that. In Chinese community we usually use NGINX SNI shunting for Chinese to search.

My own opinion is that I don't recommend to use the same VPS for site building and proxying. maybe your country is different you can consider it by yourself. If the Chinese firewall blocks port 443 of my VPS for example. If the firewall in China blocks port 443 of my VPS, for example, the VPS will not be able to be used to build a website.

**Comment by chika0801** [comment]
> Can you also explain what is meant by steal_oneself and nginx_sni_shunting

Stealing your own form is done by nginx listening on port 443 and loading your own SSL certificate. In the section about proxy knowledge, the knowledge is that it is assumed that at this point the SSL certificate on the server side will be NGINX since it is loaded by NGINX, so there is a notion that the TLS fingerprint will be NGINX. Because Xray is in the GO language. If XRAY is listening on port 443 and the TLS fingerprint is GO, it may not be rigorously verified that this is a feature. So there is a form of stealing yourself.

If your country's firewall is not that strict, you don't have to use the REALITY form of steal yourself.

I use it myself because since the author has a new feature, we try to use the newest way in China. We are build your own VPS users, it's a niche group, most of the users in China buy the proxy service provided by Chinese people to access the website. As individual users, the starting point is a hobby for new technology.

**Comment by uaudith** [comment]
Thank you for the explanation. 
I checked the Nginx configs for shunting, and here is a part I don't understand. What happens to the traffic when it does not map with either chika.example.com or example.com
```
upstream default_backend {
        server 127.0.0.1:8011;
    }
```

```
server {
        listen                     127.0.0.1:8011 ssl proxy_protocol;

        ssl_reject_handshake       on;

        ssl_protocols              TLSv1.2 TLSv1.3;
    }
```

My use case is different, we have content-based internet plans in our country which are cheaper. For example, there are internet plans for zoom.us and some isps filter the traffic using the sni.
Currently, I am using vless + tls + ws, with sni as zoom.us (flow none). With allow_insecure from the client side. For security reasons, I think I should use reality right?

**Comment by chika0801** [comment]
```
server {
        listen                     127.0.0.1:8011 ssl proxy_protocol;

        ssl_reject_handshake       on;

        ssl_protocols              TLSv1.2 TLSv1.3;
    }
```

In that example, the purpose of the NGINX configuration above is to prevent others from scanning the IP of your VPS with a tool (the XTLS repository has a scanning tool program) or from exposing the domain name contained in the SSL certificate of your VPS when you access it with https://IP. You VPS will not be a target site for someone else's dest.

**Comment by chika0801** [comment]
> with sni as zoom.us (flow none). With allow_insecure from the client side. For security reasons, I think I should use reality right?

Read your description. This kind of in China area, is when using the cell phone signal network of the telecom carrier to visit a specific web site, without counting the traffic consumed by the cell phone. This kind of usage is also found in China region. But in our country nowadays, cell phone traffic is very cheap, about 3 USD, and there are 20-40G of cell phone traffic per month, not many people use it. As for you to use it like this, you have turned on the Allow unsecured connections, parameter in the XRAY configuration. If you don't turn it on is it not possible to achieve free traffic usage? If it is indeed not possible, you still only have to turn it on. Allow unsecured connections is usually not turned on in any of the common ways we combine protocols. My knowledge is that it is when issuing SSL certificates yourself that the client turns this parameter on.

**Comment by uaudith** [comment]
So which flow do you recommend for that use case. ? 
I was not using reality. Without reality, TLS can't verify the fake sni we put in. Is that correct.

**Comment by chika0801** [comment]
You want to realize the function of free cell phone traffic, the form of protocol combination, usually only xxx+ws+TLS xxx+ws these 2 kinds.

As for the use of REALITY, your country does not have a strict firewall system, so do not use it for the time being. It depends on your own country to use which protocol is good or not to use to decide.

**Comment by uaudith** [comment]
Thank you
