### ISSUE TITLE
Seeking the Best Reality Configuration: gRPC, H2 or Vision?

### ISSUE THREAD

**Issue by AmirHosseinCV** [chika0801/Xray-examples#4]
I appreciate your efforts in introducing the Reality configurations on GitHub. I'm curious to know which configuration of Reality is most resistant to censorship. In my experience, the Reality + gRPC configuration has been effective, but I've heard that it may not be the best option and that Reality + Vision could be superior. However, I've noticed that when using Reality + Vision on certain servers, it tends to be detected more quickly, whereas Reality + gRPC remains undetected for longer. 

Could you possibly recommend a reliable resource for further learning about these configurations?

**Comment by chika0801** [comment]
The following views are from use in mainland China:

The combined form of VLESS + gRPC/H2 + TLS and the combined form of VLESS + gRPC/H2 + REALITY (stealing itself), I think they are the same in terms of effectiveness.

They are because they cannot use VISION flow control. So they can't solve the problem of TLS IN TLS being checked (Xray maintainers and some other core platform maintainers have different views on whether such checking is arranged at the level of China's national firewall, so I won't expand on that here).

But because gRPC/H2 is in the form of multiplexing, it can alleviate (and increase the difficulty of censorship). The feedback that using the gRPC/H2 combo in mainland China has resulted in the ports of one's VPS being blocked is basically non-existent (my personal summary)

With REALITY, it requires the client to pick uTLS. with TLS, the client is optional uTLS, which I recommend picking as well.

From the configuration form TLS combination is generally NGINX front listening port.

VLESS+VISION+REALITY and VLESS+VISION+REALITY (steal yourself)

Because of the ability to use VISION flow control, dealing with the TLS IN TLS problem, but less multiplexing characteristics, (gRPC/H2 multiplexing characteristics require VPS to the mainland China line network quality to be good, the lower the delay is better, usually not recommended in the line to the mainland China is very poor on the use of VPS)

If you use REALITY, does not come with the form of stealing their own, then the choice of DEST target site, is a trick. Maybe you think with REALITY is blocked and other cases and target site selection. Also not using Steal Yourself is to address the fact that there is a SNI whitelist blocking mechanism in your region. the DEST target site picks a site within the whitelist.

As for you are not in mainland China, how to use, according to your own actual situation to decide. If you have other questions, please add questions.

**Comment by AmirHosseinCV** [comment]
I appreciate your detailed clarifications!
Wish you the best of luck ❤️
